export enum ResultCodeEnum {
  Success = 0,
  PartialSuccess = 1,
  NotPaid = 2,
  UserEmailExists = 10,
  CompanyEmailExists = 11,
  NotAdmin = 20,
  NotAllowed = 30,
  NotFound = 404,
  NotManager = 50,
  ExceedLimits = 60,
  Failed = 70,
  UserDisabled = 80,
  UserNotValidated = 90,
  AccountantExists = 910,
  LockedOut = 71,
  ServiceError = 98,
  AlreadyExists = 1006,
  InvalidCredentials = 4,
  AdditionalInformationNeeded = 5,
  InvalidPinCode = 6,
  NotVerifiedInvoice = 92,
  ConfigCardLimitExceeded = 2001
}
